using Avalonia.Controls.Chrome;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ValveKeyValue;
using UtfUnknown;

namespace NekoVpk.Core
{
    public class AddonInfo
    {
        [KVProperty("AddonAuthor")]
        public string? Author { get; set; }

        [KVProperty("AddonTitle")]
        public string? Title { get; set; }

        [KVProperty("AddonVersion")]
        public string? Version { get; set; }

        [KVProperty("AddonDescription")]
        public string? Description { get; set; }

        [KVProperty("addonURL0")]
        public string? Url0 { get; set; }

        [KVProperty("nekovpk_7zname")]
        public string? NekoVpk7zName { get; set; }

        [KVProperty("nekovpk_active7z")]
        public string? NekoVpkActive7z { get; set; }

        [KVProperty("addonLink")]
        public string? Link { get; set; }

        [KVProperty("addonDate")]
        public string? Date { get; set; }

        [KVProperty("addonSteamAppID")]
        public string? SteamAppId { get; set; }

        [KVProperty("addonImage0")]
        public string? Image0 { get; set; }

        public static AddonInfo Load(byte[] data)
        {
            KVSerializerOptions options = new()
            {
                HasEscapeSequences = true,
                Encoding = TextEncodingHelper.Detect(data)
            };

            var kvs = KVSerializer.Create(KVSerializationFormat.KeyValues1Text);

            return kvs.Deserialize<AddonInfo>(new MemoryStream(data), options);
        }

        private static string Escape(string value) => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r\n", "\\n")
            .Replace("\n", "\\n")
            .Replace("\r", "\\n");

        public byte[] ToBytes()
        {
            var sb = new StringBuilder();
            sb.Append("// Generated by NekoVpk\n");
            sb.Append("AddonInfo\n");
            sb.Append("{\n");

            void WriteField(string key, string? value)
            {
                if (string.IsNullOrEmpty(value)) return;
                sb.Append($"\t{key}\t\t\"{Escape(value)}\"\n");
            }

            WriteField("addonSteamAppID", SteamAppId);
            WriteField("addontitle", Title);
            WriteField("addonauthor", Author);
            WriteField("addonLink", Link);
            WriteField("addonDate", Date);

            sb.Append("}\n");
            return Encoding.UTF8.GetBytes(sb.ToString());
        }

        private static int FindRootClosingBraceIndex(string text)
        {
            int depth = 0;
            bool inString = false;
            int lastTopLevelClose = -1;

            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];

                if (inString)
                {
                    if (c == '\\' && i + 1 < text.Length)
                    {
                        i++;
                        continue;
                    }
                    if (c == '"') inString = false;
                    continue;
                }

                if (c == '/' && i + 1 < text.Length && text[i + 1] == '/')
                {
                    while (i < text.Length && text[i] != '\n' && text[i] != '\r')
                        i++;
                    continue;
                }

                switch (c)
                {
                    case '"':
                        inString = true;
                        break;
                    case '{':
                        depth++;
                        break;
                    case '}':
                        depth--;
                        if (depth == 0)
                            lastTopLevelClose = i;
                        break;
                }
            }

            return lastTopLevelClose;
        }

        public static byte[] UpdateActive7z(byte[] data, string newActive)
        {
            var encoding = TextEncodingHelper.Detect(data, strict: true);
            string text = encoding.GetString(data);

            text = Regex.Replace(text, @"(?i)[ \t]*""?nekovpk_active7z""?\s+""[^""]*""[ \t]*\r?\n?", "");

            int lastBrace = FindRootClosingBraceIndex(text);
            if (lastBrace != -1)
            {
                string insert = $"\tnekovpk_active7z\t\"{newActive}\"\n";
                text = text.Insert(lastBrace, insert);
            }
            else
            {
                text += $"\nnekovpk_active7z\t\"{newActive}\"\n";
            }
            return encoding.GetBytes(text);
        }

        private static byte[] SetOrAppendKeyValue(byte[] data, string key, string value)
        {
            var encoding = TextEncodingHelper.Detect(data, strict: true);
            string text = encoding.GetString(data);

            text = Regex.Replace(text, $@"(?i)[ \t]*""?{Regex.Escape(key)}""?\s+""[^""]*""[ \t]*\r?\n?", "");

            int lastBrace = FindRootClosingBraceIndex(text);
            string insert = $"\t{key}\t\"{Escape(value)}\"\n";
            if (lastBrace != -1)
            {
                text = text.Insert(lastBrace, insert);
            }
            else
            {
                text += $"\n{key}\t\"{Escape(value)}\"\n";
            }
            return encoding.GetBytes(text);
        }

        public static byte[] SetLinkAndDate(byte[] data, string? link, string? date)
        {
            if (string.IsNullOrWhiteSpace(link) || string.IsNullOrWhiteSpace(date)) return data;
            var result = SetOrAppendKeyValue(data, "addonLink", link);
            result = SetOrAppendKeyValue(result, "addonDate", date);
            return result;
        }
    }
}